taskManager/taskManager/urls.py
"""Конфигурация URL диспетчера задач

Список `urlpatterns` направляет URL-адреса в представления. Для получения дополнительной информации см.:
     https://docs.djangoproject.com/en/3.2/topics/http/urls/
Примеры:
Представления функций
     1. Добавить импорт: из представлений импорта my_app
     2. Добавить URL-адрес в urlpatterns: path('', views.home, name='home')
Представления на основе классов
     1. Добавить импорт: from other_app.views import Home
     2. Добавить URL-адрес в шаблоны URL-адресов: path('', Home.as_view(), name='home')
Включение другой конфигурации URL
     1. Импорт функции include(): из django.urls import include, path
     2. Добавить URL-адрес в urlpatterns: path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, re_path
from tasks import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('add_task', views.new),
    path('show_tasks', views.show_tasks),
    path('edit_task/<int:id>', views.edit_task),
    path('update_task/<int:id>', views.update_task),
    path('delete_task/<int:id>', views.kill_task),
    path('status/<int:id>', views.status),
    path('timestamp/<int:id>', views.timestamp),
    path('show_timestamps', views.show_timestamps),
    path('timestamp_search', views.timestamp_search),
    path('delete_timestamp/<int:id>', views.delete_timestamp),
    path('edit_timestamp/<int:id>', views.edit_timestamp),
    path('update_timestamp/<int:id>', views.update_timestamp),
	  path('show_time_dashboard', views.show_time_dashboard),
    path('show_task_dashboard', views.show_task_dashboard),
	  re_path(r'^$', views.index, name='index'),
]

taskManager/tasks/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('', views.index, name='index'),
]

taskManager/tasks/models.py
from django.db import models
import math

# Создание модели.
STATUSES = (
    ('в процессе', 'В процессе'),
    ('завершенный', 'Завершенный'),
)

TIMER_STATE = (
    ('Запустить таймер', 'запустить таймер'),
    ('Остановить таймер', 'остановить  таймер'),
)

class Timestamp(models.Model):
    task = models.ForeignKey('Task', on_delete=models.CASCADE, null=True)
    begin_time = models.DateTimeField(blank=True, null=True)
    end_time = models.DateTimeField()
    
    def elapsed_time(self):
        return math.floor(((self.end_time - self.begin_time).total_seconds()/60))
    class Meta:
        db_table = "timestamps"

class Task(models.Model):
    task_name = models.CharField(max_length=100)
    task_description = models.TextField()
    timer_state = models.CharField(max_length=17, choices=TIMER_STATE, default='Запустить таймер') #Используется, чтобы определить, должна ли задача отслеживать время для создания метки времени.
    begin_time = models.DateTimeField(blank=True, null=True) #Требуется для записи времени начала временных меток. 
    project = models.CharField(max_length=100)
    status = models.CharField(max_length=11, choices=STATUSES, default='в процессе')
    class Meta:
        db_table = "tasks"

taskManager/tasks/forms.py
from django import forms
from tasks.models import Task, Timestamp

#Переопределить dateinput и datetimeinput, чтобы django мог читать html-селекторы date и datetime.
class DateTimeInput(forms.DateTimeInput):
    input_type = 'datetime-local'
    
class DateInput(forms.DateInput):
    input_type = 'date'

#Добавить новую задачу
class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["task_name", "task_description", "project", "status"]
        
class UpdateTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["task_name", "task_description", "project"]
        
class StatusForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["status"]

#Фильтр задач в списке меток времени        
class TimestampSearchForm(forms.Form):
    task_name = forms.CharField(label="id_task_name", max_length=100)

#Обновить форму временной метки
class UpdateTsForm(forms.ModelForm):
    class Meta:
        model = Timestamp
        fields = ["begin_time", "end_time"]
        widgets = {'begin_time' : DateTimeInput(), 'end_time' : DateTimeInput()}   
        
#Селектор недели/месяца      
class DateFilter(forms.Form):
    day = forms.DateField(label="date_filter", widget=DateInput())

taskManager/tasks/views.py
from django.shortcuts import render, redirect
from tasks.forms import TaskForm, UpdateTaskForm, StatusForm, TimestampSearchForm, UpdateTsForm, DateFilter
from tasks.models import Task, Timestamp
from django.utils import timezone
from collections import defaultdict
from django.db.models import Sum
from datetime import timedelta, date, datetime
import pytz
import math

# Создание views.
#При входе на главную страницу (127.0.0.1/8000/) автоматически перенаправляется на страницу show_tasks
def index(request):
	return redirect("/show_tasks")
    
#добавить страницу задачи
def new(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show_tasks')
            except:
                pass
    else:
        form = TaskForm()
    return render(request,'add_task.html',{'form':form})

    
def show_tasks(request):
    tasks = Task.objects.all().order_by('-id')
    return render(request, "show_tasks.html", {'tasks':tasks})

#показать страницу редактирования задачи   
def edit_task(request, id):
    tasks = Task.objects.get(id=id)
    form = UpdateTaskForm(initial={'task_name':tasks.task_name, 'task_description':tasks.task_description, 'project':tasks.project})
    return render(request, "edit_task.html", {'tasks':tasks, 'form':form})

#редактирование задачи и обновление бд
def update_task(request, id):
    tasks = Task.objects.get(id=id)
    if request.method == "POST":
        form = UpdateTaskForm(request.POST, instance=tasks)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show_tasks')
            except:
                pass
    else:
        form = UpdateTaskForm(initial={'task_name':tasks.task_name, 'task_description':tasks.task_description, 'project':tasks.project})   
    return render(request, "edit_task.html", {'tasks':tasks, 'form':form})

#удалить задачу
def kill_task(request, id):
    task = Task.objects.get(id=id)
    task.delete()
    return redirect("/show_tasks")

#обновить статус задачи
def status(request, id):
    tasks = Task.objects.get(id=id)
    form = StatusForm(request.POST, instance=tasks)
    form.save()
    return redirect("/show_tasks")

#Создать новую временную метку для задачи    
def timestamp(request, id):
    task = Task.objects.get(id=id)
    #Если состояние таймера «Запустить таймер», задача не имеет активной временной метки, поэтому установливается begin_time и состояние таймера меняется на «Остановить таймер».
    if(task.timer_state == 'Запустить таймер'):
        task.begin_time = timezone.now()
        task.timer_state = "Остановить таймер"
        task.save()
    #Если состояние таймера «Остановить таймер», метка времени уже запущена, создаётся новый объект метки времени и состояние таймера меняется на «Запустить таймер».
    else:
        new_ts = Timestamp(task=task, begin_time=task.begin_time, end_time=timezone.now())
        task.timer_state = "Запустить таймер"
        task.save()
        new_ts.save()
    return redirect("/show_tasks")

#Фильтр задач в списке меток времени    
def timestamp_search(request):
    form = TimestampSearchForm(request.POST)
    if form.is_valid():
        timestamps = Timestamp.objects.filter(task__task_name=form.cleaned_data['task_name']).order_by('-begin_time')
        return render(request, "show_timestamps.html", {'timestamps':timestamps})
    return redirect("/show_timestamps")
    
def show_timestamps(request):
    timestamps = Timestamp.objects.all().order_by('-id')
    return render(request, "show_timestamps.html", {'timestamps':timestamps})

def delete_timestamp(request, id):
    ts = Timestamp.objects.get(id=id)
    # Попытки сохранить поиск. Если запрос пришел из show_timestamps, он пришел из полного списка временных меток, поэтому возвращается полный список
    if "show_timestamps" in request.META['HTTP_REFERER']:  
        ts.delete()
        return redirect("/show_timestamps")
    # в противном случае повторить поиск задачи и вернуть отфильтрованный список
    else:
        ts.delete()
        timestamps = Timestamp.objects.filter(task__task_name=ts.task.task_name).order_by('-begin_time')
        return render(request, "show_timestamps.html", {'timestamps':timestamps})

#тот же процесс, что и edit_task
def edit_timestamp(request, id):
    timestamp=Timestamp.objects.get(id=id)
    form = UpdateTsForm()
    return render(request, 'edit_timestamp.html', {'timestamp':timestamp, 'form':form})
    
#Поскольку редактирование, обновление — это двухэтапный процесс, нельзя использовать HTTP_REFERER для сохранения поиска, поэтому редактирование всегда будет возвращать полный Журнал активности.
def update_timestamp(request, id):
    timestamp = Timestamp.objects.get(id=id)
    if request.method == 'POST':
        form = UpdateTsForm(request.POST, instance=timestamp)
        if form.is_valid() and form.cleaned_data['begin_time'] < form.cleaned_data['end_time']:
            try:
                form.save()
                return redirect("/show_timestamps")
            except:
                pass
    form = UpdateTsForm()
    return render(request, "edit_timestamp.html", {'form':form, 'timestamp':timestamp})

def show_time_dashboard(request):
    tasks = Task.objects.all().order_by('-id')
    ts_total = {}
    ts_week = {}
    ts_month = {}
    if request.method == 'POST':
        #Если указана дата, извлечь год, месяц и начало недели
        date_form = DateFilter(request.POST)
        if date_form.is_valid():
            year = date_form.cleaned_data['day'].year
            month = date_form.cleaned_data['day'].month
            week_start = date_form.cleaned_data['day'] - timedelta(days=date_form.cleaned_data['day'].weekday())
    #В противном случае используется сегодняшняя дата
    else:
        date_form = DateFilter()
        year = date.today().year
        month = date.today().month
        week_start = date.today() - timedelta(days=date.today().weekday())
    week_end = week_start + timedelta(days=6)
    #Рассчитать начало и конец недели и месяца как локализованную дату и время. Это упрощает вычисления со значениями временных меток, поскольку все они одного типа.
    #Также исправляет ошибку, из-за которой, поскольку даты и время всегда хранятся в базе данных как время UTC, datetime.day будет отключен на 1, если дата и время выпадают поздно ночью или рано утром из-за изменения времени.
    week_start_time = pytz.timezone('US/Eastern').localize(datetime.combine(week_start, datetime.min.time()))
    week_end_time = pytz.timezone('US/Eastern').localize(datetime.combine(week_end, datetime.max.time()))
    month_start_time = pytz.timezone('US/Eastern').localize(datetime(year, month, 1, 0, 0))
    month_end_time = pytz.timezone('US/Eastern').localize(datetime((year+1 if month==12 else year), (1 if month==12 else month+1), 1, 0, 0))
    #Поиск проектов для фильтрации
    projects = set()
    for task in tasks:
        timestamps = Timestamp.objects.filter(task__id=task.id)
        projects.add(task.project)
        #Общее время на каждую задачу
        ts_total[task.id] = 0
        #Время, потраченное на задачу на этой неделе
        ts_week[task.id] = 0
        #Время, потраченное на задачу в этом месяце
        ts_month[task.id] = 0
        for timestamp in timestamps:
            ts_total[task.id] += timestamp.elapsed_time()
            #Если временная метка начинается и заканчивается в течение недели, вся временная метка добавляется к еженедельному времени.
            if timestamp.begin_time >= week_start_time and timestamp.end_time <= week_end_time:
                ts_week[task.id] += timestamp.elapsed_time()
            #Если Журнал активности начинаются до недели, но заканчиваются в течение недели, добавляется только время между началом недели и концом временной метки.
            if timestamp.begin_time < week_start_time and timestamp.end_time <= week_end_time and timestamp.end_time > week_start_time:
                ts_week[task.id] += math.floor((timestamp.end_time - week_start_time).total_seconds()/60)
            #Если временная метка начинается в течение недели, но заканчивается после недели, добавляется только время от начала временной метки до конца недели.
            if timestamp.begin_time <= week_end_time and timestamp.begin_time >= week_start_time and timestamp.end_time > week_end_time:
                ts_week[task.id] += math.floor((week_end_time - timestamp.begin_time).total_seconds()/60) + 1 #Нужен +1, потому что week_end_time в 23:59, нужно добавить последнюю минуту
            #Если отметка времени начинается до недели и заканчивается после недели, добавляется вся неделя
            if timestamp.begin_time < week_start_time and timestamp.end_time > week_end_time:
                ts_week[task.id] += math.floor((week_end_time - week_start_time).total_seconds()/60) + 1
            #Та же логика для месяца, что и для недели
            if timestamp.begin_time >= month_start_time and timestamp.end_time <= month_end_time:
                ts_month[task.id] += timestamp.elapsed_time()
            if timestamp.begin_time < month_start_time and timestamp.end_time <= month_end_time and timestamp.end_time > month_start_time:
                ts_month[task.id] += math.floor((timestamp.end_time - month_start_time).total_seconds()/60)
            if timestamp.begin_time >= month_start_time and timestamp.end_time > month_end_time and timestamp.begin_time < month_end_time:
                ts_month[task.id] += math.floor((month_end_time - timestamp.begin_time).total_seconds()/60)
            if timestamp.begin_time < month_start_time and timestamp.end_time > month_end_time:
                ts_month[task.id] += math.floor((month_end_time - month_start_time).total_seconds()/60)
    
    p_total = {}
    p_week = {}
    p_month = {}
    #Выполняет тот же процесс, что и для задач, но циклически перебирает разные проекты.
    for project in projects:

taskManager/tasks/templates/add_task.html
<!DOCTYPE html>
<head>  
    <meta charset="UTF-8">  
    <title>Добавить задачу</title> 
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 

	<style>

		html *{
    		font-family: Verdana !important;
		}	

		header {
          background: #343a40;
        }

        header::after {
          content: '';
          display: table;
          clear: both;
        }

        .logo {
          float: left;
          padding-top: 15px;
		  margin-left: 10px;
		  padding-bottom: 10px;
          border: none;
        }

        nav {
          float: right;
        }

        nav ul {
          margin: 0;
          padding: 0;
          list-style: none;
        }

        nav li {
		  color: #ffffff;
          display: inline-block;
          margin-left: 20px;
		  margin-right: 20px;
		  padding-top: 20px;
          position: relative;
        }

        nav a {
          color: #ffffff;
        }

        nav a:hover {
          color: #00ff00;
        }

        nav a::before {
          content: '';
          display: block;
          height: 5px;
          background-color: #444;

          position: absolute;
          top: 0;
          width: 0%;

          transition: all ease-in-out 250ms;
        }

        nav a:hover::before {
          width: 100%;
        }

		h3 {
			color: #f8f9fa;
		}

        form {
    		display: inline;
		}

	</style>
</head>  
<body> 
	<header>
		<div class="container_h">
			<h3 class="logo"><b>Добавить задачу</b></h3>

			<nav>
				<ul>
					<li><a href="/show_tasks">Список задач</a></li>
					<li><a href="/show_timestamps">Журнал активности</a></li>
					<li><a href="/show_task_dashboard">Панель управления задачами</a></li>
					<li><a href="/show_time_dashboard">Панель мониторинга времени</a></li>
				</ul>
			</nav>

		</div>
	</header> 
<div style="padding-left: 10px;">
<form method="POST" action="/add_task">  
    {% csrf_token %}    
<br>    
    <h3 style="color: black;">Введите данные</h3>   
    <label>Название задачи:</label>  
		{{ form.task_name }}  
	<br>
	  
    <label>Описание задачи:</label>  
	<br>
		{{ form.task_description }}  
	<br>
	  
    <label>Проект:</label>  
		{{ form.project }}  
	<br>
	  
    <label>Статус:</label>   
		{{ form.status }}  
	<br>
	  
    <button type="submit">Создать</button>   
</form>  
<form method="POST" action="/show_tasks">
    {% csrf_token %}
    <button type="submit">Отмена</button>
</form>
</div>
</body>  
</html>  

taskManager/tasks/templates/edit_task.html
<!DOCTYPE html>
<head>  
    <meta charset="UTF-8">  
    <title>Редактировать задачу</title> 
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 

	<style>

		html *{
    		font-family: Verdana !important;
		}	

		header {
          background: #343a40;
        }

        header::after {
          content: '';
          display: table;
          clear: both;
        }

        .logo {
          float: left;
          padding-top: 15px;
		  margin-left: 10px;
		  padding-bottom: 10px;
          border: none;
        }

        nav {
          float: right;
        }

        nav ul {
          margin: 0;
          padding: 0;
          list-style: none;
        }

        nav li {
		  color: #ffffff;
          display: inline-block;
          margin-left: 20px;
		  margin-right: 20px;
		  padding-top: 20px;
          position: relative;
        }

        nav a {
          color: #ffffff;
        }

        nav a:hover {
          color: #00ff00;
        }

        nav a::before {
          content: '';
          display: block;
          height: 5px;
          background-color: #444;

          position: absolute;
          top: 0;
          width: 0%;

          transition: all ease-in-out 250ms;
        }

        nav a:hover::before {
          width: 100%;
        }

		h3 {
			color: #f8f9fa;
		}

	</style>
</head>  
<body> 
	<header>
		<div class="container_h">
			<h3 class="logo"><b>Редактировать задачу</b></h3>

			<nav>
				<ul>
          <li><a href="/show_tasks">Список задач</a></li>
					<li><a href="/show_timestamps">Журнал активности</a></li>
					<li><a href="/show_task_dashboard">Панель управления задачами</a></li>
					<li><a href="/show_time_dashboard">Панель мониторинга времени</a></li>
				</ul>
			</nav>

		</div>
	</header>

<div style="padding-left: 10px;">
<form method="POST" action="/update_task/{{tasks.id}}">
	<div class="form-group">
	<thead class="thead-dark"> 
	{% csrf_token %}
<br>  
    <label>Название задачи:</label>
		{{ form.task_name }} 
	<br>
	
    <label>Описание задачи:</label>
	<br>
        {{ form.task_description }}  
	<br>	
    <label>Проект:</label>   
        {{form.project }}  
	<br>
	  
    <button type="submit">Обновить</button>  
	</div> 
</form> 
</div> 
</body>  
</html>  

taskManager/tasks/templates/edit_timestamp.html
<!DOCTYPE html>
<head>  
    <meta charset="UTF-8">  
    <title>Редактировать отметку времени</title>	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 
	<style>

		html *{
    		font-family: Verdana !important;
		}	

		header {
          background: #343a40;
        }

        header::after {
          content: '';
          display: table;
          clear: both;
        }

        .logo {
          float: left;
          padding-top: 15px;
		  margin-left: 10px;
		  padding-bottom: 10px;
          border: none;
        }

        nav {
          float: right;
        }

        nav ul {
          margin: 0;
          padding: 0;
          list-style: none;
        }

        nav li {
		  color: #ffffff;
          display: inline-block;
          margin-left: 20px;
		  margin-right: 20px;
		  padding-top: 20px;
          position: relative;
        }

        nav a {
          color: #ffffff;
        }

        nav a:hover {
          color: #00ff00;
        }

        nav a::before {
          content: '';
          display: block;
          height: 5px;
          background-color: #444;

          position: absolute;
          top: 0;
          width: 0%;

          transition: all ease-in-out 250ms;
        }

        nav a:hover::before {
          width: 100%;
        }

		h3 {
			color: #f8f9fa;
		}

		form {
    		display: inline;
		}

	</style>
	
</head>  
    
 
	<body>  
		<header>
			<div class="container_h">
				<h3 class="logo"><b>Редактировать Журнал активности</b></h3>

				<nav>
					<ul>
						<li><a href="/show_tasks">Список задач</a></li>
						<li><a href="/show_timestamps">Журнал активности</a></li>
						<li><a href="/show_task_dashboard">Панель управления задачами</a></li>
						<li><a href="/show_time_dashboard">Панель мониторинга времени</a></li>
					</ul>
				</nav>


			</div>
		</header>
		
		<div style="padding-left: 10px;">
			<form method="POST" action="/update_timestamp/{{timestamp.id}}"> 
				{% csrf_token %}
				<br>  
				<label>Время начала:</label>  
					{{ form.begin_time }}  
				<br>
				<br>
				
				<label>Конечное время:</label> 
					{{ form.end_time }}    
				<br>
				<br>
				<button type="submit">Обновить</button>   
			</form>

			<form method="POST" action="/show_timestamps">
				{% csrf_token %}
				<button type="submit">Отмена</button>
			</form>
		</div>
	</body>  
</html>  

taskManager/tasks/templates/index.html
<!DOCTYPE html>
<head>  
    <meta charset="UTF-8">  
    <title>Добавить задачу</title> 
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 

	<style>

		html *{
    		font-family: Verdana !important;
		}	

		header {
          background: #343a40;
        }

        header::after {
          content: '';
          display: table;
          clear: both;
        }

        .logo {
          float: left;
          padding-top: 15px;
		  margin-left: 10px;
		  padding-bottom: 10px;
          border: none;
        }

        nav {
          float: right;
        }

        nav ul {
          margin: 0;
          padding: 0;
          list-style: none;
        }

        nav li {
		  color: #ffffff;
          display: inline-block;
          margin-left: 20px;
		  margin-right: 20px;
		  padding-top: 20px;
          position: relative;
        }

        nav a {
          color: #ffffff;
        }

        nav a:hover {
          color: #00ff00;
        }

        nav a::before {
          content: '';
          display: block;
          height: 5px;
          background-color: #444;

          position: absolute;
          top: 0;
          width: 0%;

          transition: all ease-in-out 250ms;
        }

        nav a:hover::before {
          width: 100%;
        }

		h3 {
			color: #f8f9fa;
		}

        form {
    		display: inline;
		}

	</style>
</head>  
<body> 
	<header>
		<div class="container_h">
			<h3 class="logo"><b>Добавить задачу</b></h3>
			<nav>
				<ul>
					<li><a href="/show_tasks">Список задач</a></li>
					<li><a href="/show_timestamps">Журнал активности</a></li>
					<li>Панель управления задачами</li>
					<li>Панель мониторинга времени</li>
				</ul>
			</nav>
		</div>
	</header> 
<div style="padding-left: 10px;">
<form method="POST" action="/new">  
    {% csrf_token %}    
<br>    
    <h3 style="color: black;">Введите данные</h3>   
    <label>Название задачи:</label>  
		{{ form.task_name }}  
	<br>
	  
    <label>Описание задачи:</label>  
	<br>
		{{ form.task_description }}  
	<br>
	  
    <label>Проект:</label>  
		{{ form.project }}  
	<br>
	  
    <label>Статус:</label>   
		{{ form.status }}  
	<br>
	  
    <button type="submit">Создать</button>   
</form>  
<form method="POST" action="/show_tasks">
    {% csrf_token %}
    <button type="submit">Отмена</button>
</form>
</div>
</body>  
</html>  

taskManager/tasks/templates/show_tasks.html
<!DOCTYPE html>
<head>  
    <meta charset="UTF-8">  
    <title>Диспетчер задач</title>	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 
	
	<style>

		html *{
    		font-family: Verdana !important;
		}	

		header {
          background: #343a40;
        }

        header::after {
          content: '';
          display: table;
          clear: both;
        }

        .logo {
          float: left;
          padding-top: 15px;
		  margin-left: 10px;
		  padding-bottom: 10px;
          border: none;
        }

        nav {
          float: right;
        }

        nav ul {
          margin: 0;
          padding: 0;
          list-style: none;
        }

        nav li {
		  color: #ffffff;
          display: inline-block;
          margin-left: 20px;
		  margin-right: 20px;
		  padding-top: 20px;
          position: relative;
        }

        nav a {
          color: #ffffff;
        }

        nav a:hover {
          color: #00ff00;
        }

        nav a::before {
          content: '';
          display: block;
          height: 5px;
          background-color: #444;

          position: absolute;
          top: 0;
          width: 0%;

          transition: all ease-in-out 250ms;
        }

        nav a:hover::before {
          width: 100%;
        }

		h3 {
			color: #f8f9fa;
		}

	</style>

	
</head>  


<body>

<header>
	<div class="container_h">
		<h3 class="logo"><b>Список задач</b></h3>
		<nav>
			<ul>
        <li><a href="/show_tasks">Список задач</a></li>
        <li><a href="/show_timestamps">Журнал активности</a></li>
        <li><a href="/show_task_dashboard">Панель управления задачами</a></li>
        <li><a href="/show_time_dashboard">Панель мониторинга времени</a></li>
			</ul>
		</nav>
	</div>
</header>
<br>
<center><a href="/add_task">Добавить новую задачу</a></center>
<br>
<table class="table">  
    <thead class="thead-dark">  
    <tr>  
        <th>Название задачи</th>  
        <th>Описание задачи</th> 
		<th>Проект</th>
        <th>Отметка времени</th>  
        <th>Статус</th>  
		<th>Изменить статус</th>
        <th>Действия</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for task in tasks %}  
    <tr>  
        <td>{{ task.task_name }}</td>  
        <td>{{ task.task_description }}</td>  
        <td>{{ task.project }}</td>  
		<td>
			<form method="POST" action="/timestamp/{{task.id}}">
				{% csrf_token %}
				<button type="submit">{{ task.timer_state }}</button>				
			</form>
		</td>
        <td>{{ task.status }}</td>  
		<td>
			<form method="POST" action="/status/{{task.id}}">
				{% csrf_token %}
				<select id="id_status" name="status">
					<option value="в процессе">В процессе</option>
					<option value="завершенный">Завершенный</option>
				</select>
				<button type="submit">Обновить статус</button>				
			</form>
		</td>
        <td>  
            <a href="/edit_task/{{ task.id }}">Редактировать</a>
			<b> | </b>  
            <a href="/delete_task/{{ task.id }}">Удалить</a>
        </td> 
    </tr>
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
</body>  
</html>  